logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          donation-alerts:
            client-name: donationalerts-client
            provider: donationalerts-provider
            client-id: 12047
            client-secret: XukduNifyT0V5PgSXmfO4r8ukBXtsR1R8MGlFcas
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - oauth-donation-index
              - oauth-user-show
            client-authentication-method: client_secret_post
        provider:
          donationalerts-provider:
            authorization-uri: https://www.donationalerts.com/oauth/authorize
            token-uri: https://www.donationalerts.com/oauth/token
            user-info-uri: https://www.donationalerts.com/api/v1/user/oauth
            user-name-attribute: data